mod common;

use common::*;

#[test]
fn list_and_add_write_the_golden_files() {
    let dir = project();
    let alice = key(dir.path(), "alice.key");
    let bob = key(dir.path(), "bob.key");
    let original = access_text(&[("alice", "dev", &alice.recipient)]);
    write_access(dir.path(), &original);

    let listed = yett(dir.path(), &["access", "list"]);
    assert_eq!(listed.status.code(), Some(0), "{}", stderr(&listed));
    assert_eq!(listed.stdout, original.as_bytes());

    let added = yett(dir.path(), &["access", "add", "bob", "dev", &bob.recipient]);
    assert_eq!(added.status.code(), Some(0), "{}", stderr(&added));
    assert!(
        String::from_utf8_lossy(&added.stdout).contains("access sync"),
        "{}",
        String::from_utf8_lossy(&added.stdout)
    );
    let expected = format!(
        "# generated by yett — edit secrets-access.yaml instead\ncreation_rules:\n  - path_regex: \\.yett/secrets\\.dev\\.enc\\.yaml$\n    key_groups: [{{ age: [{}, {}] }}]\n",
        alice.recipient, bob.recipient
    );
    assert_eq!(
        std::fs::read(dir.path().join(".sops.yaml")).unwrap(),
        expected.as_bytes()
    );
}

#[test]
fn removal_rotates_the_data_key_and_preserves_plaintext() {
    let dir = project();
    let alice = key(dir.path(), "alice.key");
    let bob = key(dir.path(), "bob.key");
    write_access(
        dir.path(),
        &access_text(&[
            ("alice", "dev", &alice.recipient),
            ("bob", "dev", &bob.recipient),
        ]),
    );
    let secret_path = dir.path().join(".yett/secrets.dev.enc.yaml");
    std::fs::write(
        &secret_path,
        yett::sops::encrypt_yaml(PLAINTEXT, &alice.recipient).unwrap(),
    )
    .unwrap();

    let first_sync = yett(
        dir.path(),
        &["--identity", alice.path.to_str().unwrap(), "access", "sync"],
    );
    assert_eq!(first_sync.status.code(), Some(0), "{}", stderr(&first_sync));
    let bob_identity =
        yett::identity::Identity::from_secret_key(&std::fs::read_to_string(&bob.path).unwrap())
            .unwrap();
    let before = std::fs::read_to_string(&secret_path).unwrap();
    assert!(yett::sops::decrypt_yaml(&before, &bob_identity).is_ok());

    let removed = yett(
        dir.path(),
        &[
            "--identity",
            alice.path.to_str().unwrap(),
            "access",
            "remove",
            "bob",
        ],
    );
    assert_eq!(removed.status.code(), Some(0), "{}", stderr(&removed));
    let after = std::fs::read_to_string(&secret_path).unwrap();
    assert!(yett::sops::decrypt_yaml(&after, &bob_identity).is_err());
    let alice_identity =
        yett::identity::Identity::from_secret_key(&std::fs::read_to_string(&alice.path).unwrap())
            .unwrap();
    let plaintext = yett::sops::decrypt_yaml(&after, &alice_identity).unwrap();
    assert_eq!(plaintext["db"]["password"].as_str(), Some("unchanged"));
    assert!(!after.contains("unchanged"));
    println!("remove bob: exit 0");
    println!("bob decrypt: failed");
    println!("alice decrypt: succeeded; plaintext unchanged");
}

#[test]
fn prod_removal_is_gated_and_uses_forward_only_wording() {
    let dir = project();
    let owner = key(dir.path(), "owner.key");
    let successor = key(dir.path(), "successor.key");
    let original = access_text(&[
        ("owner", "prod", &owner.recipient),
        ("successor", "prod", &successor.recipient),
    ]);
    write_access(dir.path(), &original);
    let secret_path = dir.path().join(".yett/secrets.prod.enc.yaml");
    std::fs::write(
        &secret_path,
        yett::sops::encrypt_yaml(PLAINTEXT, &owner.recipient).unwrap(),
    )
    .unwrap();
    let shared = yett(
        dir.path(),
        &["--identity", owner.path.to_str().unwrap(), "access", "sync"],
    );
    assert_eq!(shared.status.code(), Some(0), "{}", stderr(&shared));

    let blocked = yett(dir.path(), &["access", "remove", "owner"]);
    assert_eq!(blocked.status.code(), Some(1));
    assert_eq!(
        std::fs::read_to_string(dir.path().join(".yett/secrets-access.yaml")).unwrap(),
        original
    );
    let blocked_text = stderr(&blocked);
    assert!(
        blocked_text.contains("keeps access to everything already committed"),
        "{blocked_text}"
    );
    assert!(blocked_text.contains("no access to future changes"));
    assert!(blocked_text.contains("prod values must now be rotated at their source"));
    assert!(!blocked_text.contains("revoked"));

    let forced = yett(
        dir.path(),
        &[
            "--identity",
            successor.path.to_str().unwrap(),
            "access",
            "remove",
            "owner",
            "--force-prod",
        ],
    );
    assert_eq!(forced.status.code(), Some(0), "{}", stderr(&forced));
    let output = String::from_utf8_lossy(&forced.stdout);
    assert!(output.contains("no access to future changes"));
    assert!(!output.contains("revoked"));
    assert!(
        !output.contains("rerun with --force-prod"),
        "the success message must not ask for a flag already used: {output}"
    );
    let after = std::fs::read_to_string(&secret_path).unwrap();
    let owner_identity =
        yett::identity::Identity::from_secret_key(&std::fs::read_to_string(&owner.path).unwrap())
            .unwrap();
    let successor_identity = yett::identity::Identity::from_secret_key(
        &std::fs::read_to_string(&successor.path).unwrap(),
    )
    .unwrap();
    assert!(yett::sops::decrypt_yaml(&after, &successor_identity).is_ok());
    assert!(yett::sops::decrypt_yaml(&after, &owner_identity).is_err());
    println!("prod removal without --force-prod: exit 1");
    println!("{}", blocked_text.trim());
    println!("prod removal with --force-prod: exit 0");
    println!("{}", output.trim());
}

#[test]
fn removing_the_sole_prod_recipient_requires_a_replacement() {
    let dir = project();
    let owner = key(dir.path(), "owner.key");
    let list = access_text(&[("owner", "prod", &owner.recipient)]);
    write_access(dir.path(), &list);
    let secret_path = dir.path().join(".yett/secrets.prod.enc.yaml");
    std::fs::write(
        &secret_path,
        yett::sops::encrypt_yaml(PLAINTEXT, &owner.recipient).unwrap(),
    )
    .unwrap();
    let before = std::fs::read_to_string(&secret_path).unwrap();

    let out = yett(
        dir.path(),
        &[
            "--identity",
            owner.path.to_str().unwrap(),
            "access",
            "remove",
            "owner",
            "--force-prod",
        ],
    );

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    assert!(
        stderr(&out).contains("replacement recipient"),
        "{}",
        stderr(&out)
    );
    assert_eq!(
        std::fs::read_to_string(dir.path().join(".yett/secrets-access.yaml")).unwrap(),
        list,
        "a refused removal must not change the list"
    );
    assert_eq!(
        std::fs::read_to_string(&secret_path).unwrap(),
        before,
        "a refused removal must not change the ciphertext"
    );
}

#[test]
fn removing_an_unknown_handle_is_an_error() {
    let dir = project();
    let alice = key(dir.path(), "alice.key");
    let list = access_text(&[("alice", "dev", &alice.recipient)]);
    write_access(dir.path(), &list);

    let out = yett(dir.path(), &["access", "remove", "bobb"]);

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    assert!(
        stderr(&out).contains("not in the access list"),
        "{}",
        stderr(&out)
    );
    assert_eq!(
        std::fs::read_to_string(dir.path().join(".yett/secrets-access.yaml")).unwrap(),
        list
    );
}

#[test]
fn removing_one_recipient_rotates_the_wrapped_key_for_the_others() {
    let dir = project();
    let alice = key(dir.path(), "alice.key");
    let bob = key(dir.path(), "bob.key");
    let carol = key(dir.path(), "carol.key");
    let secret_path = dir.path().join(".yett/secrets.dev.enc.yaml");
    std::fs::write(
        &secret_path,
        yett::sops::encrypt_yaml(PLAINTEXT, &alice.recipient).unwrap(),
    )
    .unwrap();
    write_access(
        dir.path(),
        &access_text(&[
            ("alice", "dev", &alice.recipient),
            ("bob", "dev", &bob.recipient),
            ("carol", "dev", &carol.recipient),
        ]),
    );
    let added = yett(
        dir.path(),
        &["--identity", alice.path.to_str().unwrap(), "access", "sync"],
    );
    assert_eq!(added.status.code(), Some(0), "{}", stderr(&added));
    let before = std::fs::read_to_string(&secret_path).unwrap();
    let bob_identity = identity_at(&bob.path);
    let bob_before = wrapped_data_key(&before, &bob_identity);

    let removed = yett(
        dir.path(),
        &[
            "--identity",
            alice.path.to_str().unwrap(),
            "access",
            "remove",
            "carol",
        ],
    );
    assert_eq!(removed.status.code(), Some(0), "{}", stderr(&removed));

    let after = std::fs::read_to_string(&secret_path).unwrap();
    assert_ne!(
        wrapped_data_key(&after, &bob_identity),
        bob_before,
        "the data key wrapped for bob must be a different key after carol is removed"
    );
    let yaml: serde_yaml::Value = serde_yaml::from_str(&after).unwrap();
    assert!(
        yaml["sops"]["age"]
            .as_sequence()
            .unwrap()
            .iter()
            .all(|entry| entry["recipient"].as_str() != Some(&carol.recipient)),
        "carol must not appear in the rewrapped metadata"
    );
}

#[test]
fn verification_reports_config_and_recipient_mismatches_as_exit_four() {
    let dir = project();
    let alice = key(dir.path(), "alice.key");
    let bob = key(dir.path(), "bob.key");
    write_access(
        dir.path(),
        &access_text(&[("alice", "dev", &alice.recipient)]),
    );
    let access =
        yett::access::AccessList::load(&dir.path().join(".yett/secrets-access.yaml")).unwrap();
    let edited = format!("{}# hand edit\n", access.render_sops_config());
    let error = yett::access::verify(&access, &edited, &dir.path().join(".yett")).unwrap_err();
    assert!(matches!(error, yett::Error::AccessMismatch(_)));
    assert_eq!(error.exit_code(), 4);
    println!("hand-edited .sops.yaml: AccessMismatch, exit 4");

    std::fs::write(
        dir.path().join(".yett/secrets.dev.enc.yaml"),
        yett::sops::encrypt_yaml(PLAINTEXT, &bob.recipient).unwrap(),
    )
    .unwrap();
    let error = yett::access::verify(
        &access,
        &access.render_sops_config(),
        &dir.path().join(".yett"),
    )
    .unwrap_err();
    assert!(matches!(error, yett::Error::AccessMismatch(_)));
    assert_eq!(error.exit_code(), 4);
    println!("extra file recipient: AccessMismatch, exit 4");
}
