use std::os::unix::process::CommandExt;
use std::path::Path;
use std::process::{Command, Output};

extern "C" {
    fn setsid() -> i32;
}

fn yett(dir: &Path, args: &[&str]) -> Output {
    let mut command = Command::new(env!("CARGO_BIN_EXE_yett"));
    command.current_dir(dir).args(args);
    for name in ["YETT_IDENTITY", "ROPS_AGE", "ROPS_AGE_KEY_FILE"] {
        command.env_remove(name);
    }
    command.output().unwrap()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).into_owned()
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).into_owned()
}

const EMPTY_SOPS: &str =
    "# generated by yett — edit secrets-access.yaml instead\ncreation_rules:\n";

#[test]
fn init_scaffolds_the_project() {
    let dir = tempfile::tempdir().unwrap();

    let out = yett(dir.path(), &["init"]);

    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    let access_path = dir.path().join(".yett/secrets-access.yaml");
    let sops_path = dir.path().join(".sops.yaml");
    assert!(access_path.is_file());
    assert!(dir.path().join(".env.refs").is_file());

    let sops = std::fs::read_to_string(&sops_path).unwrap();
    assert_eq!(sops, EMPTY_SOPS);
    let access = yett::access::AccessList::load(&access_path).unwrap();
    assert_eq!(sops, access.render_sops_config());
}

#[test]
fn a_second_init_exits_one_and_changes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    assert_eq!(yett(dir.path(), &["init"]).status.code(), Some(0));

    let sops_path = dir.path().join(".sops.yaml");
    let access_path = dir.path().join(".yett/secrets-access.yaml");
    let sops_before = std::fs::read(&sops_path).unwrap();
    let access_before = std::fs::read(&access_path).unwrap();

    let out = yett(dir.path(), &["init"]);

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    assert!(
        stderr(&out).contains("refusing to overwrite"),
        "{}",
        stderr(&out)
    );
    assert_eq!(std::fs::read(&sops_path).unwrap(), sops_before);
    assert_eq!(std::fs::read(&access_path).unwrap(), access_before);
}

#[test]
fn init_records_the_requested_tiers() {
    let dir = tempfile::tempdir().unwrap();

    let out = yett(dir.path(), &["init", "--tiers", "dev,staging"]);

    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
    assert!(stdout(&out).contains("dev, staging"), "{}", stdout(&out));
}

#[test]
fn init_rejects_duplicate_and_invalid_tiers() {
    for tiers in ["dev,dev", "dev,bad/name", "dev,", ""] {
        let dir = tempfile::tempdir().unwrap();
        let out = yett(dir.path(), &["init", "--tiers", tiers]);
        assert_eq!(out.status.code(), Some(1), "{tiers}: {}", stderr(&out));
        assert!(!dir.path().join(".sops.yaml").exists(), "{tiers}");
    }
}

#[test]
fn check_passes_right_after_init() {
    let dir = tempfile::tempdir().unwrap();
    assert_eq!(yett(dir.path(), &["init"]).status.code(), Some(0));

    let out = yett(dir.path(), &["check"]);

    assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
}

#[test]
fn keygen_register_without_an_access_list_exits_one_and_writes_no_identity() {
    let dir = tempfile::tempdir().unwrap();
    let out = Command::new(env!("CARGO_BIN_EXE_yett"))
        .current_dir(dir.path())
        .args(["keygen", "--tier", "dev", "--register", "you"])
        .env("XDG_CONFIG_HOME", dir.path())
        .env("HOME", dir.path())
        .env_remove("YETT_IDENTITY")
        .output()
        .unwrap();

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    assert!(stderr(&out).contains("yett init"), "{}", stderr(&out));
    assert!(!dir.path().join("yett/dev.key.age").exists());
    assert!(!dir.path().join(".sops.yaml").exists());
}

#[test]
fn init_with_handle_refuses_multiple_tiers_and_writes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    let out = yett(
        dir.path(),
        &["init", "--tiers", "dev,staging", "--handle", "you"],
    );

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    let text = stderr(&out);
    assert!(text.contains("dev"), "{text}");
    assert!(text.contains("staging"), "{text}");
    assert!(!dir.path().join(".yett").exists());
    assert!(!dir.path().join(".sops.yaml").exists());
}

#[test]
fn init_with_handle_without_a_tty_exits_one_and_writes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    let mut command = Command::new(env!("CARGO_BIN_EXE_yett"));
    command
        .current_dir(dir.path())
        .args(["init", "--tiers", "dev", "--handle", "you"])
        .env("XDG_CONFIG_HOME", dir.path())
        .env("HOME", dir.path());
    command.env_remove("YETT_IDENTITY");
    unsafe {
        command.pre_exec(|| {
            setsid();
            Ok(())
        });
    }

    let out = command.output().unwrap();

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    let text = stderr(&out);
    assert!(text.contains("yett init"), "{text}");
    assert!(text.contains("yett keygen"), "{text}");
    assert!(!dir.path().join(".yett").exists());
    assert!(!dir.path().join(".sops.yaml").exists());
}

#[test]
fn keygen_without_a_tty_exits_one_and_writes_nothing() {
    let dir = tempfile::tempdir().unwrap();
    let mut command = Command::new(env!("CARGO_BIN_EXE_yett"));
    command
        .current_dir(dir.path())
        .args(["keygen", "--tier", "dev"])
        .env("XDG_CONFIG_HOME", dir.path())
        .env("HOME", dir.path());
    command.env_remove("YETT_IDENTITY");
    unsafe {
        command.pre_exec(|| {
            setsid();
            Ok(())
        });
    }

    let out = command.output().unwrap();

    assert_eq!(out.status.code(), Some(1), "{}", stderr(&out));
    assert!(!dir.path().join("yett/dev.key.age").exists());
    assert!(!dir.path().join(".yett/secrets-access.yaml").exists());
}
